In [3]:
from keras.models import load_model
from Class_Image import Image
from os.path import abspath
from Class_training import *
from Model_comparisons import comparisons_model
from os.path import abspath, join
import numpy as np

import matplotlib.pyplot as plt
import tensorflow as tf
from tensorflow.keras.applications import VGG19
import keras
from tensorflow.keras import Input, Model

In [2]:
print("Loading data...")

DATA_FOLDER ="Z:\Comparisons_npy"#"D:\\Ottawa\\Comparisons_npy"
folder_path = abspath("Examples/Training_results/Simple")

data_left = np.load(join(DATA_FOLDER, "train", "train_left_224.npy"))
data_right = np.load(join(DATA_FOLDER, "train", "train_right_224.npy"))
data_label = np.load(join(DATA_FOLDER, "train", "train_labels_224.npy"))
labels_score = np.load(join(DATA_FOLDER, "train", "train_labels_score_224.npy"))
train_data = [data_left, data_right]
print("Done")

Loading data...
Done


In [4]:
img_size=224
vgg = VGG19(weights='imagenet', include_top=False, input_shape=(img_size, img_size, 3))
vgg_feature_extractor = Model(inputs=vgg.input, outputs=vgg.get_layer('block3_pool').output)
vgg.summary()

Model: "vgg19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_1 (InputLayer)         [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     

In [ ]:
batch_size = 20

In [26]:
a=vgg(data_left[0:batch_size])



ResourceExhaustedError: OOM when allocating tensor with shape[3651,224,224,64] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc [Op:Conv2D]

In [4]:
np.concatenate((None, np.zeros([2,3])), 1).shape

ValueError: zero-dimensional arrays cannot be concatenated

In [25]:
a.numpy().shape

(3, 7, 7, 512)

In [2]:
data_left.shape

NameError: name 'data_left' is not defined

In [23]:
vgg = VGG19(weights='imagenet', include_top=False, input_shape=(img_size, img_size, 3))
vgg_no_train = Model(inputs=vgg.input, outputs=vgg.get_layer('block3_pool').output)

def create_embeddings(data, model, batch_size=20):
    len_data = data.shape[0]
    a = vgg(data_left[0:batch_size])
    
    for i in range(batch_size, len_data, batch_size):
        v = vgg(data_left[i:i+batch_size])
        a = np.concatenate((a, v), 0)
        
    return a

a=create_embeddings(data_left)
print("done")

done


In [24]:
a.shape

(3651, 7, 7, 512)

In [29]:
save_folder = "Z:/embeddings"
np.save((save_folder), a)

In [27]:
print("sdf")

sdf


In [5]:
load=np.load("Z:/embeddjings.npy")

In [7]:
load.shape

(3651, 7, 7, 512)

In [8]:
np.load("Z:/embeddjings.npy")

FileNotFoundError: [Errno 2] No such file or directory: 'Z:/embeddjings.npy'

In [13]:
vgg.get_layer('block3_pool')

In [75]:
vgg_trainable = 'block3_pool'
vgg_include_until = 'block4_pool'

vgg = VGG19(weights='imagenet', include_top=False, input_shape=(img_size, img_size, 3))
vgg_no_train = Model(inputs=vgg.input, outputs=vgg.get_layer(vgg_trainable).output)
#vgg_trainable = Model(inputs=vgg.get_layer(vgg_trainable).input, outputs=vgg.get_layer(vgg_include_until).output)

In [76]:
print("...")
flag = False
vgg_include_until="block4_pool" 
inp = Input(shape = vgg.get_layer(vgg_trainable).output.shape[1:])
x=inp
for l in vgg.layers:
    if(flag):
        x=l(x)
        print(i.output.shape)
        print(i.name)
        
    if(l.name == vgg_trainable):
        flag = True
        
vgg_trainable = Model(inp, x)
print("done")

...
(None, 7, 7, 512)
block5_pool
(None, 7, 7, 512)
block5_pool
(None, 7, 7, 512)
block5_pool
(None, 7, 7, 512)
block5_pool
(None, 7, 7, 512)
block5_pool
(None, 7, 7, 512)
block5_pool
(None, 7, 7, 512)
block5_pool
(None, 7, 7, 512)
block5_pool
(None, 7, 7, 512)
block5_pool
(None, 7, 7, 512)
block5_pool
done


In [78]:
v=vgg_no_train(np.zeros([1,224,224,3]))
v = vgg_trainable(v)
v

<tf.Tensor: shape=(1, 7, 7, 512), dtype=float32, numpy=
array([[[[0.22428545, 0.        , 0.        , ..., 0.        ,
          1.2261467 , 0.        ],
         [0.19310719, 0.        , 0.        , ..., 0.        ,
          1.0247742 , 0.        ],
         [0.2489618 , 0.        , 0.        , ..., 0.        ,
          1.0189773 , 0.        ],
         ...,
         [0.26546925, 0.        , 0.        , ..., 0.        ,
          1.0825343 , 0.        ],
         [0.20535553, 0.        , 0.        , ..., 0.        ,
          1.2031858 , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          1.2036499 , 0.        ]],

        [[0.10066706, 0.        , 0.        , ..., 0.        ,
          1.1666315 , 0.        ],
         [0.24121898, 0.        , 0.        , ..., 0.        ,
          0.96015793, 0.        ],
         [0.2602612 , 0.        , 0.        , ..., 0.        ,
          0.9658231 , 0.        ],
         ...,
         [0.26629496, 0.        

In [80]:
vgg(np.zeros([1,224,224,3]))

<tf.Tensor: shape=(1, 7, 7, 512), dtype=float32, numpy=
array([[[[0.22428545, 0.        , 0.        , ..., 0.        ,
          1.2261467 , 0.        ],
         [0.19310719, 0.        , 0.        , ..., 0.        ,
          1.0247742 , 0.        ],
         [0.2489618 , 0.        , 0.        , ..., 0.        ,
          1.0189773 , 0.        ],
         ...,
         [0.26546925, 0.        , 0.        , ..., 0.        ,
          1.0825343 , 0.        ],
         [0.20535553, 0.        , 0.        , ..., 0.        ,
          1.2031858 , 0.        ],
         [0.        , 0.        , 0.        , ..., 0.        ,
          1.2036499 , 0.        ]],

        [[0.10066706, 0.        , 0.        , ..., 0.        ,
          1.1666315 , 0.        ],
         [0.24121898, 0.        , 0.        , ..., 0.        ,
          0.96015793, 0.        ],
         [0.2602612 , 0.        , 0.        , ..., 0.        ,
          0.9658231 , 0.        ],
         ...,
         [0.26629496, 0.        

In [73]:
vgg_no_train.summary()
vgg_trainable.summary()

Model: "model_23"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_24 (InputLayer)        [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0  

In [54]:
vgg.summary()

Model: "vgg19"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_13 (InputLayer)        [(None, 224, 224, 3)]     0         
_________________________________________________________________
block1_conv1 (Conv2D)        (None, 224, 224, 64)      1792      
_________________________________________________________________
block1_conv2 (Conv2D)        (None, 224, 224, 64)      36928     
_________________________________________________________________
block1_pool (MaxPooling2D)   (None, 112, 112, 64)      0         
_________________________________________________________________
block2_conv1 (Conv2D)        (None, 112, 112, 128)     73856     
_________________________________________________________________
block2_conv2 (Conv2D)        (None, 112, 112, 128)     147584    
_________________________________________________________________
block2_pool (MaxPooling2D)   (None, 56, 56, 128)       0     